This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and 
in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users 
but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, 
feel free to open an issue at https://github.com/rougier/numpy-100. 
File automatically generated. See the documentation to update questions/answers/hints programmatically.

1. Import the numpy package under the name np (★☆☆)
hint: import … as

2. Create a null vector of size 10 (★☆☆)
hint: np.zeros

3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
hint: array[4]

4. Create a vector with values ranging from 10 to 49 (★☆☆)
hint: arange

5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
hint: reshape

6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
hint: np.nonzero

7. Create a 3x3 identity matrix (★☆☆)
hint: np.eye

8. Create a 3x3x3 array with random values (★☆☆)
hint: np.random.random

9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
hint: min, max

10. Create a random vector of size 30 and find the mean value (★☆☆)
hint: mean

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
hint: np.diag

12. Normalize a 5x5 random matrix (★☆☆)
hint: (x -mean)/std

13. How to find common values between two arrays? (★☆☆)
hint: np.intersect1d

14. Create a random vector of size 10 and sort it (★★☆)
hint: sort

15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
hint: argmax

16. Subtract the mean of each row of a matrix (★★☆)
hint: mean(axis=,keepdims=)

17. How to get the n largest values of an array (★★★)
Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
hint: np.where

In [2]:
import numpy as np
# Create a null vector of size 10 (★☆☆)
np.zeros((10)) 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
import numpy as np
x = np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
#Create a vector with values ranging from 10 to 49 (★☆☆)
#hint: arange
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
# 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#hint: reshape
a = np.arange(0,9).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
#6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#hint: np.nonzero
x = np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4]),)


In [7]:
#7. Create a 3x3 identity matrix (★☆☆)
# hint: np.eye
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
#8. Create a 3x3x3 array with random values (★☆☆)
np.random.random((3,3,3))


array([[[0.81565886, 0.94925339, 0.6217706 ],
        [0.87500995, 0.3669573 , 0.49534489],
        [0.32718894, 0.76974144, 0.00238832]],

       [[0.83206212, 0.50981381, 0.99570229],
        [0.1746624 , 0.83057785, 0.86251498],
        [0.93558295, 0.70956963, 0.99018618]],

       [[0.89305449, 0.86023359, 0.98519268],
        [0.67772607, 0.2068177 , 0.47802654],
        [0.28625144, 0.47338773, 0.00794745]]])

In [9]:
#9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#hint: min, max
import numpy as np
x = np.random.random((10,10))
print(x)
Min_value = np.min(x)
print("Minimum Value: ",Min_value)
Max_Value = np.max(x)
print("Maximum Value: ", Max_Value)
      

[[0.40156573 0.50351499 0.77826835 0.70474232 0.87311645 0.91977586
  0.62267795 0.66386516 0.64845403 0.33157321]
 [0.88025078 0.60015138 0.37829318 0.31866766 0.2432588  0.35895199
  0.05322416 0.02473905 0.72366014 0.63298896]
 [0.54777589 0.42072172 0.91935207 0.14138369 0.58084027 0.74889663
  0.56938794 0.62716199 0.4913666  0.56503501]
 [0.05225431 0.00991173 0.44959109 0.44938054 0.39248757 0.57616675
  0.61718176 0.94398766 0.90981801 0.39802517]
 [0.66995062 0.89534011 0.63783693 0.96534782 0.2074307  0.79219011
  0.83209962 0.13128223 0.8780118  0.53016236]
 [0.18831582 0.20610902 0.34757585 0.75474861 0.78486759 0.22009873
  0.87834419 0.65549138 0.66174971 0.80579615]
 [0.20846669 0.20963179 0.51637763 0.54892329 0.40264397 0.91643763
  0.38156292 0.46579009 0.32318759 0.35654689]
 [0.82115507 0.21921287 0.20197614 0.08297078 0.82051975 0.4353329
  0.56277776 0.59118273 0.91409604 0.60682167]
 [0.14042415 0.68357546 0.15561475 0.20950888 0.62385659 0.86420496
  0.69954333 

In [10]:
#10. Create a random vector of size 30 and find the mean value (★☆☆)
#hint: mean
x = np.random.random(30)
print(x)
print("Mean: ",np.mean(x))

[0.69246139 0.66421069 0.82859063 0.12263383 0.4965947  0.02669675
 0.11227157 0.37219424 0.21471412 0.60668728 0.42195115 0.48906316
 0.57564425 0.47103101 0.01039216 0.16084332 0.44700763 0.07334209
 0.7936051  0.94517207 0.47620935 0.82620706 0.1541809  0.01443283
 0.88089834 0.56167316 0.60067866 0.42648891 0.62602759 0.83987805]
Mean:  0.4643927314479336


In [11]:
#11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#hint: np.diag
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [12]:
#12. Normalize a 5x5 random matrix (★☆☆)
#hint: (x -mean)/std
x = np.random.random((5,5))
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

[[0.30396368 0.91901808 0.6557586  0.62891784 0.60794964]
 [0.82213829 0.48765169 0.9410083  0.81418487 0.64740218]
 [0.82591506 0.51781684 0.98805262 0.66550878 0.03600278]
 [0.67378109 0.83540679 0.5034503  0.82549324 0.70280743]
 [0.60839916 0.49690873 0.21007237 0.05480081 0.7765802 ]]
After normalization:
[[0.2814568  0.92748852 0.65096993 0.62277733 0.60075307]
 [0.82572937 0.47439629 0.95058628 0.81737537 0.64219264]
 [0.82969636 0.50608071 1.         0.66121119 0.        ]
 [0.66990013 0.83966614 0.4909906  0.82925329 0.70038839]
 [0.60122523 0.48411956 0.18283664 0.0197448  0.77787673]]


In [13]:
#13. How to find common values between two arrays? (★☆☆)
#hint: np.intersect1d
x = np.array([0, 10, 20, 40, 60])
print("x", x)
y = [10, 30, 40]
print("y", y)
print("common values:", np.intersect1d(x, y))

x [ 0 10 20 40 60]
y [10, 30, 40]
common values: [10 40]


In [14]:
#14. Create a random vector of size 10 and sort it (★★☆)
#hint: sort
x = np.random.random(10)
print(np.sort(x))

[0.29249987 0.29507506 0.29643297 0.35071932 0.49770675 0.57770104
 0.83039799 0.85223144 0.88912148 0.99778762]


In [15]:
#15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#hint: argmax
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.41661735 0.56227188 0.47541943 0.79660499 0.62974324 0.
 0.62443416 0.51780362 0.0611901  0.51751204]


In [16]:
#16. Subtract the mean of each row of a matrix (★★☆)
#hint: mean(axis=,keepdims=)
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)

Original matrix:

[[0.32859237 0.07246847 0.60374004 0.21641269 0.63975602 0.99165532
  0.44610255 0.87405856 0.13085634 0.0723492 ]
 [0.19255254 0.10753274 0.93379466 0.39357838 0.07728299 0.15974243
  0.13726764 0.61441899 0.32023678 0.22017636]
 [0.12418292 0.56710127 0.63562534 0.30084052 0.85831617 0.07054777
  0.01721244 0.91355233 0.72861411 0.38611841]
 [0.57488437 0.74206752 0.03160492 0.44872098 0.81575492 0.56036203
  0.06385533 0.46997306 0.84196368 0.95428392]
 [0.4903158  0.19095877 0.72988053 0.94925972 0.71369637 0.9731175
  0.66718333 0.47518879 0.86963459 0.62042104]]


In [17]:
#17. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5 
#hint: np.argsort | np.argpartition
np.argsort(Z)[-n:]

array([1668, 7020,  668, 1484, 9738])

In [20]:
#18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
#hint: np.where
x = np.random.randint(1, 10, (5, 3))
print(x, '\n\n', np.where(x > 4, x**2, x))


[[9 7 7]
 [7 9 4]
 [9 3 2]
 [7 8 6]
 [6 9 4]] 

 [[81 49 49]
 [49 81  4]
 [81  3  2]
 [49 64 36]
 [36 81  4]]
